CREATE TABLE [dbo].[KATEGORILER](
	[KATEGORIID] [smallint] IDENTITY(1,1) NOT NULL,
	[KATEGORIAD] [varchar](50) NULL,
 CONSTRAINT [PK_KATEGORILER] PRIMARY KEY CLUSTERED 
(
	[KATEGORIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[MUSTERILER](
	[MUSTERIID] [int] IDENTITY(1,1) NOT NULL,
	[MUSTERIAD] [varchar](50) NULL,
	[MUSTERISOYAD] [varchar](50) NULL,
 CONSTRAINT [PK_MUSTERILER] PRIMARY KEY CLUSTERED 
(
	[MUSTERIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[SATISLAR](
	[SATISID] [int] IDENTITY(1,1) NOT NULL,
	[URUN] [int] NULL,
	[MUSTERI] [int] NULL,
	[ADET] [tinyint] NULL,
	[FIYAT] [decimal](18, 2) NULL,
 CONSTRAINT [PK_SATISLAR] PRIMARY KEY CLUSTERED 
(
	[SATISID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SATISLAR]  WITH CHECK ADD  CONSTRAINT [FK_SATISLAR_MUSTERILER] FOREIGN KEY([MUSTERI])
REFERENCES [dbo].[MUSTERILER] ([MUSTERIID])
GO

ALTER TABLE [dbo].[SATISLAR] CHECK CONSTRAINT [FK_SATISLAR_MUSTERILER]
GO

ALTER TABLE [dbo].[SATISLAR]  WITH CHECK ADD  CONSTRAINT [FK_SATISLAR_URUNLER] FOREIGN KEY([URUN])
REFERENCES [dbo].[URUNLER] ([URUNID])
GO

ALTER TABLE [dbo].[SATISLAR] CHECK CONSTRAINT [FK_SATISLAR_URUNLER]
GO

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[URUNLER](
	[URUNID] [int] IDENTITY(1,1) NOT NULL,
	[URUNAD] [varchar](50) NULL,
	[URUNKATEGORI] [smallint] NULL,
	[URUNFIYAT] [decimal](18, 2) NULL,
	[URUNMARKA] [varchar](50) NULL,
	[URUNSTOK] [tinyint] NULL,
 CONSTRAINT [PK_URUNLER] PRIMARY KEY CLUSTERED 
(
	[URUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[URUNLER]  WITH CHECK ADD  CONSTRAINT [FK_URUNLER_KATEGORILER] FOREIGN KEY([URUNKATEGORI])
REFERENCES [dbo].[KATEGORILER] ([KATEGORIID])
GO

ALTER TABLE [dbo].[URUNLER] CHECK CONSTRAINT [FK_URUNLER_KATEGORILER]
GO